Implement place koma
kouchou/kimura pull request #3
Opened 2018-06-15 19:04 UTC by kouchou

クリックすると歩を打つ処理を実装した
その他使いそうな関数を実装した

2018-06-15 23:25 UTC, machiyashiki requested changes

2018-06-15 23:25 UTC, machiyashiki commented on main.js
> +      $element.id = "cell" + (colIndex * 9 + rowIndex + 1);
getIDbyCoordinates作ったのになぜ使わん？

2018-06-15 23:25 UTC, machiyashiki commented on main.js
> +var placeKoma = function(owner, kind, cellId) {
3つ目の引数xとyにしたほうがわかりやすい
デバッグでcellId=47とか言われてもどこか分らんくて多分困る

2018-06-15 23:25 UTC, machiyashiki commented on main.js
> +createKoma(initPosition);
main文は最後に書く

2018-06-15 23:25 UTC, machiyashiki commented on main.js
>    [{"owner": "white", "kind": "KY"}, {"owner": "white", "kind": "KE"}, {"owner": "white", "kind": "GI"}, {"owner": "white", "kind": "KI"}, {"owner": "white", "kind": "GY"}, {"owner": "white", "kind":
駒の名称略すのやめたほうがいいと思う

2018-06-15 23:26 UTC, machiyashiki requested changes

2018-06-15 23:26 UTC, machiyashiki commented on main.js
> +var getIDbyCoordinates = function(x, y) {
ID ->Id

2018-06-16 13:06 UTC, kouchou commented on main.js
> +      $element.id = "cell" + (colIndex * 9 + rowIndex + 1);
座標がこの時点ではわからない

2018-06-16 13:07 UTC, kouchou commented on main.js
>    [{"owner": "white", "kind": "KY"}, {"owner": "white", "kind": "KE"}, {"owner": "white", "kind": "GI"}, {"owner": "white", "kind": "KI"}, {"owner": "white", "kind": "GY"}, {"owner": "white", "kind":
わかった。でも書き換えるのちょっとめんどいからまた今度やる。

2018-06-16 17:30 UTC, merged